title: Fanglin Linda Liu
googlescholar : https://scholar.google.com/citations?user=70xlCGkAAAAJ&hl=en
cv : true
email : fanglin_liu@berkeley.edu
logo: /assets/img/Linda.JPG
description: Fanglin's personal website.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme